name: Laravel CI-CS

on:
  push:
    branches: [ "main", "develop", "feature/*" ]

jobs:
  tests-and-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, curl, libxml, sqlite3

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run Tests and Security Scan
        env:
          APP_KEY: base64:t6YvO+K/fF9O9k8XW+L/vQ5M1N2B3C4D5E6F7G8H9I0=
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: |
          php artisan config:clear
          composer audit
          php artisan test